# Generated by Django 5.2.17 on 2026-08-13 19:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    # Pinned to old, stable core migrations rather than whatever was latest when this was generated:
    # makemigrations defaults to the newest migration in the installed Nautobot, which would make this
    # migration unappliable on the minimum supported version. These two are the same targets the
    # sibling migrations (0029/0030) use, and are far below any supported Nautobot's migration set.
    # BackupVersion needs only dcim.Device and extras.GitRepository, both of which long predate them.
    dependencies = [
        ("dcim", "0049_remove_slugs_and_change_device_primary_ip_fields"),
        ("extras", "0098_rename_data_jobresult_result"),
        ("nautobot_golden_config", "0031_alter_configplan_change_control_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="backup_retention_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goldenconfigsetting",
            name="backup_retention_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BackupVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("commit_sha", models.CharField(max_length=40)),
                ("blob_sha", models.CharField(max_length=40)),
                ("path", models.CharField(max_length=255)),
                ("authored_date", models.DateTimeField()),
                ("committer", models.CharField(blank=True, max_length=255)),
                ("message", models.CharField(blank=True, max_length=255)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="backup_versions", to="dcim.device"
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_versions",
                        to="extras.gitrepository",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backup Version",
                "verbose_name_plural": "Backup Versions",
                "ordering": ["-authored_date"],
                "indexes": [
                    models.Index(fields=["device", "-authored_date"], name="gc_bv_device_date_idx"),
                    models.Index(fields=["-authored_date"], name="gc_bv_date_idx"),
                ],
                "unique_together": {("device", "commit_sha")},
            },
        ),
    ]
